before myexception
MyException(MY EXECPT!)
myexception catched
